action_space: 18
annotate:
  game_annonate: Alien
  traj_num: 10
dataset_dir: /home/Userlist/jinyg/DATA/
eval:
  ckpt_eval: /home/Userlist/jinyg/dtmi/checkpoint/2023-09-27/0.45_trajectory_1.ckpt
  condition_dim: 512
  condition_type: raw
  enable_action: false
  enable_instruct: false
  enable_language: false
  enable_retrieval: false
  enable_trajectory: false
  eval_rtg: 100
  game_list: '1'
  max_timestep: 100 # decided by model 
  context_length: 20
  model_type: reward_conditioned
instruct_dir: /home/Userlist/jinyg/dtmi/instruct/
seed: 123
train:
  batch_size: 256
  ckpt_path: /home/Userlist/jinyg/dtmi/checkpoint/
  condition_dim: 512
  condition_type: trajectory
  context_length: 20
  enable_action: false
  enable_instruct: false
  enable_language: false
  enable_retrieval: true
  enable_trajectory: true
  epochs: 20
  game_list: '1'
  model_type: reward_conditioned
  num_buffers: 50
  num_steps: 20000 # x*10k
  trajectories_per_buffer: 1
  num_game_batch: 2