action_space: 18
annotate:
  game_annonate: Alien
  traj_num: 20
condition_dim: 512
dataset_dir: /home/Userlist/jinyg/DATA/
eval:
  action_space: 6
  ckpt_eval: /home/Userlist/jinyg/dtmi/checkpoint/0.79_raw_1.ckpt
  eval_rtg: 1000
  max_timestep: 4749
game_list: '1'
instruct_dir: /home/Userlist/jinyg/dtmi/instruct/
instruction_type: language
max_timestep: 4955
seed: 123
train:
  batch_size: 256
  ckpt_path: /home/Userlist/jinyg/dtmi/checkpoint/
  context_length: 30
  epochs: 5
  model_type: reward_conditioned
  num_buffers: 50
  num_steps: 100000
  trajectories_per_buffer: 2
