action_space: 18
annotate:
  game_annonate: Alien
  traj_num: 10
dataset_dir: /home/Userlist/jinyg/DATA/
eval:
  att_input_dim: 512
  ckpt_eval: /home/Userlist/jinyg/dtmi/checkpoint/2023-09-27/0.45_trajectory_1.ckpt
  condition_dim: 512
  device: '1'
  eval_rtg: 100
  instruction_type: trajectory
game_list: '1'
instruct_dir: /home/Userlist/jinyg/dtmi/instruct/
max_timestep: 24744
seed: 123
train:
  att_input_dim: 512
  batch_size: 256
  ckpt_path: /home/Userlist/jinyg/dtmi/checkpoint/
  condition_dim: 512
  context_length: 30
  device: 1,2,3,4
  epochs: 20
  instruction_type: trajectory
  model_type: reward_conditioned
  num_buffers: 50
  num_steps: 50000
  trajectories_per_buffer: 1

