# public
dataset_dir: '/scratch/vcis/project/dt-with-multiInst/data/'
instruct_dir: '/scratch/vcis/project/dt-with-multiInst/instruct/'
instruction_type: "raw" # raw languge trajectory instruction
seed: 123
game_list: "1"

# annonate
annotate:
  game_annonate: AirRaid
  traj_num: 20

# train
train:
  num_buffers: 50
  num_steps: 5000 # 100000
  trajectories_per_buffer: 20
  context_length: 30
  batch_size: 128
  epochs: 5
  ckpt_path: '/scratch/vcis/project/dt-with-multiInst/checkpoint'

# eval
eval:
  ckpt_eval:
  max_timestep:
  action_space:
  eval_rtg: