action_space: 6
annotate:
  game_annonate: AirRaid
  traj_num: 10
condition_dim: 512
dataset_dir: /scratch/vcis/project/dt-with-multiInst/data/
eval:
  ckpt_eval: /scratch/vcis/project/dt-with-multiInst/checkpoint/1.1288289222042118_raw.ckpt
  eval_rtg: 2000
game_list: '1'
instruct_dir: /scratch/vcis/project/dt-with-multiInst/instruct/
instruction_type: language
max_timestep: 4749
seed: 123
train:
  batch_size: 128
  ckpt_path: /scratch/vcis/project/dt-with-multiInst/checkpoint
  context_length: 30
  epochs: 5
  model_type: reward_conditioned
  num_buffers: 50
  num_steps: 500000
  trajectories_per_buffer: 20
