train:
- Zaxxon 
- QBert 
- Wizard_Of_Wor  
- Venture 
- Up_N_Down 
- Tutankham 
- Time_Pilot 
- Star_Gunner 
- Space_Invaders 

eval: 
# TRAINED
  - name: Zaxxon
    action_dim: 18
  - name: QBert
    action_dim: 6
  - name: Wizard_Of_Wor 
    action_dim: 10
  - name: Video_Pinball 
    action_dim: 9
  - name: Venture
    action_dim: 6
  - name: Up_N_Down
    action_dim: 6
  - name: Tutankham 
    action_dim: 8
  - name: Time_Pilot  
    action_dim: 10
  - name: Star_Gunner
    action_dim: 6
  - name: Space_Invaders 
    action_dim: 6
# UNSEEN    
  - name: Alien
    action_dim: 18
  - name: Air_Raid
    action_dim: 6
  - name: Breakout
    action_dim: 4
  - name: Pong
    action_dim: 6
  - name: Hero 
    action_dim: 18

#@ dt
## 310 185 170 0 0 1199 0 1610 210 177 
#! 167 337 0 -20 0
#@ language
## 1250 202 190 40 0 2239 4 2710 190 270 
#! 161 417 0 -21 15
#@ trajectory
## 1200 362 150 0 0 3120 4 1660 250 252 
#! 253 437 0 -21 7